Traceback (most recent call last):
  File "ungrib_press-taito.py", line 65, in <module>
    date=job_row['date']
  File "/homeappl/home/aliagadi/saltena_2018/wrf_management/wrf_management/ungrib.py", line 180, in update_run_table
    con.commit()
sqlite3.OperationalError: disk I/O error
