Traceback (most recent call last):
  File "ungrib_avgtsfc.py", line 89, in <module>
    un.link_grub_files(ungrib_prefixes=ungrib_source_dirs, job_path=job_path)
  File "/homeappl/home/aliagadi/saltena_2018/wrf_management/wrf_management/ungrib.py", line 180, in link_grub_files
    df.apply(lambda r: relink(r['source'], r['dest']), axis=1)
  File "/homeappl/home/aliagadi/appl_taito/miniconda3/envs/b36/lib/python3.6/site-packages/pandas/core/frame.py", line 6014, in apply
    return op.get_result()
  File "/homeappl/home/aliagadi/appl_taito/miniconda3/envs/b36/lib/python3.6/site-packages/pandas/core/apply.py", line 142, in get_result
    return self.apply_standard()
  File "/homeappl/home/aliagadi/appl_taito/miniconda3/envs/b36/lib/python3.6/site-packages/pandas/core/apply.py", line 248, in apply_standard
    self.apply_series_generator()
  File "/homeappl/home/aliagadi/appl_taito/miniconda3/envs/b36/lib/python3.6/site-packages/pandas/core/apply.py", line 277, in apply_series_generator
    results[i] = self.f(v)
  File "/homeappl/home/aliagadi/saltena_2018/wrf_management/wrf_management/ungrib.py", line 180, in <lambda>
    df.apply(lambda r: relink(r['source'], r['dest']), axis=1)
  File "/homeappl/home/aliagadi/saltena_2018/wrf_management/wrf_management/run_utilities.py", line 147, in relink
    os.remove(dest_file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/wrk/aliagadi/DONOTREMOVE/wrf_management_data/runs/run_2019_02_20/2017_12_03/ungrib_avgtsfc/ungrib_surf:2017-12-03_06'
